### ISSUE TITLE
isUrlの仕様

### ISSUE THREAD

**Issue by takuto-y** [the-labo/the#47]
- `http://example.com https://example.jp`
- `http://example.com を開く`
で`isUrl`が`true`になってしまうため、

`const PATTERNS = [/^https?:\S+$/, /^data?:\S+$/]`

へ変更して問題なければ、変更したいです。

また、`dat:`([Dat Protocol Foundation](https://dat.foundation/))は受け付けない`/^data:/`が正しいですか？

**Comment by okunishinishi** [comment]
> へ変更して問題なければ、変更したいです。

@takuto-y 問題ないっす

> また、dat:(Dat Protocol Foundation)は受け付けない/^data:/が正しいですか？

はい、正しいです。imgタグのsrc属性とか、html界隈の前提がそうなっているはずなので
