### ISSUE TITLE
the-/assets内のflatpickr.cssが更新されていない

### ISSUE THREAD

**Issue by takuto-y** [the-labo/the#58]
`package.json`内のバージョンは、`4.6.6` に変更されているのですが、[the/flatpickr.css at master · the-labo/the](https://github.com/the-labo/the/blob/master/packages/assets/assets/flatpickr/flatpickr.css) は4.6.6のものになっていないです。このファイルの更新はどのようにすれば良いのでしょうか？

https://github.com/the-labo/the/blob/8973aabd5758449709bf3baa7552d9f49afa7b8b/packages/assets/package.json#L19

**Comment by okunishinishi** [comment]
手動反映してた気がする
