### ISSUE TITLE
TheInput.Upload ipad でタップ反応なし(ダブルタップだけ反応)

### ISSUE THREAD

**Issue by sansoohan** [the-labo/the#66]
Atenet 立会作成時、
202012.0.0+321f75a0
https://github.com/realglobe-Inc/atenet/issues/1896

**Comment by FujiHaruka** [comment]
再現しませんでした。

- iPad（第７世代）
- OSバージョン 14.2

ローカルで確認する手順：

```bash
## Current directory: the-labo/the
$ npm i
$ cd packages/ui-input
$ npm i
$ npx serve doc/demo
## And you can access to the server with iPad via the local network.
```

**Comment by FujiHaruka** [comment]
もとの issue 見たら TheInput.Upload の不具合ではなかった

**Comment by FujiHaruka** [comment]
ダブルタップで反応するのは、カレンダー入力の UI で使用している flatpicker の現在の仕様ですね。 
issue に上がっていますが、Pull Request を送って採用してもらえるかどうかは運次第かもしれません。
 https://github.com/flatpickr/flatpickr/issues/1977

**Comment by okunishinishi** [comment]
@sansoohan @s-numata 上で指摘されている通り、

- そもそも TheInput.Upload の話ではない
- flatpickrの仕様である

であり、このレポジトリは直接関係ないのでクローズします
