### ISSUE TITLE
@the-/ui-list がいない？

### ISSUE THREAD

**Issue by FujiHaruka** [the-labo/the#79]
npm package は存在する https://www.npmjs.com/package/@the-/ui-list 
のに、このリポジトリ内には存在しない。

これはどこか別のリポジトリにいるんですかね？ @okunishinishi

**Comment by okunishinishi** [comment]
@FujiHaruka 用済みになってgit側からは消したような気がします

**Comment by FujiHaruka** [comment]
ほんとだ。このコミットでパッケージごと削除されていますね。わかりました、ありがとうございます。

https://github.com/the-labo/the/commit/56060e3921130561de144917bb419a90f3434dc1
